tasks:
  - init: |
      ECHO 'Installing TomBot dependencies...'
      pip install discord.py
      pip install python-dotenv
      pip install youtube_dl
    command: |
      cd Source
      python bot.py