tasks:
  - init: |
      echo 'Installing TomBot dependencies...'
      pip install discord.py
      pip install python-dotenv
      pip install youtube_dl
    command: |
      cd Source
      echo 'Remember to add your token and server name to the .env file before running!'
